{
  "hash": "116299013d559d589032c4b3db1ae63d",
  "result": {
    "engine": "jupyter",
    "markdown": "# Machine Learning Earnings Forecasts and Market Expectations {#sec-mlef}\n\nEvery earnings-based design in this part of the book needs an *expected* earnings number. The earnings surprise of @sec-sue subtracts it from reported earnings, implied cost of capital inverts a valuation model around it, and forward P/E divides price by it. For four decades the default proxy has been the analyst consensus, because analysts beat time-series models [@bradshaw2012man] and because the market appears to react to deviations from consensus [@kothari2001capital; @livnat2006comparing]. Machine learning has unsettled that default. A string of recent papers reports that statistical models can produce earnings forecasts more accurate than analysts' forecasts [@ball2018automated; @binsbergen2023man; @cao2024fundamental; @desilva2024noise], which suggests that researchers should replace the consensus with a machine forecast.\n\n@campbell2026expectations ask the obvious follow-up questions that the earlier papers mostly skipped. *Which* machine forecast? Their answer is that the claim \"machines beat analysts\" depends on modelling choices that most papers make without discussion: 79% of the 3,024 machine-learning models they estimate are *less* accurate than the analyst consensus. They then ask *why* the good models win, and find that they win by correcting predictable errors in analysts' forecasts, not by finding new information. Finally, they ask which forecast the *market* uses. Stock prices behave as if investors correct most, but not all, of the predictable analyst error, and the uncorrected part shows up in returns for up to nine months after the announcement.\n\nThis chapter lays the paper out in full and then reproduces it in three ways:\n\n1.  @sec-mlef-paper walks through the design (the 3,024-model experiment, the accuracy measure, the indirect forecasting approach, and the market-expectations test) and its results.\n2.  @sec-mlef-replication re-computes the paper's headline numbers from the authors' public replication data with independent code.\n3.  @sec-mlef-sim builds a simulation in which the true analyst bias, the true market expectation, and the true information sets are known, and shows each mechanism the paper documents: why loss function, analyst inputs, the indirect approach, and the cross-validation scheme matter, why the machine's advantage concentrates in small firms and long horizons, and what the market-expectations regression does and does not identify.\n\n@sec-mlef-vn then turns the paper into a research design for Vietnam, where analyst coverage is thin and the question \"should I use the consensus or a model?\" arises for almost every firm.\n\n::: {.callout-note title=\"Sources used in this chapter\"}\nThe paper is @campbell2026expectations, *Management Science* 72(10), 8863--8887. The full text of the published version sits behind a bot check, so the method details below come from two open sources: (i) the authors' replication package on Mendeley Data (DOI [10.17632/2pg764w6gs.1](https://doi.org/10.17632/2pg764w6gs.1), CC BY 4.0), whose table files match the published tables, and (ii) the April 2024 working-paper version, which is Chapter 2 of Harrison Ham's University of Georgia dissertation. Numbers quoted from the package are the published numbers. Where a number exists only in the working paper (the horizon table, the implied-cost-of-capital test, and the analyst-value-added analysis), the text says so, because some magnitudes changed between versions.\n:::\n\n## The Question and Why It Matters {#sec-mlef-question}\n\nAn earnings expectation can serve two different purposes, and the paper's title is a reminder that the two need not coincide.\n\n1.  **A statistical forecast.** Which number minimises the ex post forecast error? This is what matters for valuation inputs such as forward earnings and implied cost of capital [@frankel1998accounting; @hou2012implied].\n2.  **A proxy for the market's belief.** Which number do prices reflect? This is what matters for earnings-surprise and earnings-response designs, where the researcher wants $\\text{SUE}$ to measure *news to investors*.\n\nIf investors were fully rational and had access to the best statistical model, the two would coincide. If investors share analysts' biases [@bordalo2019diagnostic] or simply overweight the consensus [@so2013new], the most accurate forecast and the market's expectation diverge, and the right choice depends on the research question. @campbell2026expectations quantify both sides with the same set of forecasts.\n\n## The Paper in Detail {#sec-mlef-paper}\n\n### Data and Forecast Targets {#sec-mlef-data}\n\nThe sample is the CRSP--Compustat--I/B/E/S intersection. Analysts' forecasts are the I/B/E/S median consensus, which I/B/E/S computes on the third Thursday of each month. Two targets are forecast every month:\n\n-   **FQ**: the next quarterly EPS (I/B/E/S horizon Q1, or Q2 if Q1 has already been announced before month end). Data from January 1985.\n-   **FY2**: two-year-ahead annual EPS. Data from January 1983, as in @bradshaw2012man.\n\nBoth end in December 2020, and out-of-sample evaluation runs from June 1990. The predictor set has 77 features: the WRDS Financial Ratio Suite, five CRSP variables (price, monthly return, six-month momentum, industry momentum, log market capitalisation), and five analyst variables:\n\n| Variable | Definition |\n|----------------------------|--------------------------------------------|\n| `medestqtr`, `medest2` | Current consensus forecast for FQ / FY2 |\n| `rev_FYqtr_3m`, `rev_FY2_3m` | Three-month revision of the consensus |\n| `ibes_earnings_qtr`, `ibes_earnings_ann` | Most recently realised quarterly / annual EPS |\n| `last_Fqtrana_fe_med`, `last_F2ana_fe_med` | Most recently *realised* analyst forecast error at a comparable distance to the period end |\n| `distqtr`, `dist2` | Months between the forecast date and the fiscal period end |\n\n: Analyst-related predictors in @campbell2026expectations (working-paper Table A2). {#tbl-mlef-analyst-vars}\n\nPredictors are winsorised monthly at 1% and 99%, missing values are filled with the Fama--French 38-industry median and then the cross-sectional median, and features are standardised with training-window means and standard deviations. Firm-months with price at or below \\$1 are dropped. The final datasets hold about 1.26 million (FQ) and 1.35 million (FY2) firm-months, roughly 2,300--2,400 firms per month.\n\nThe timeline is the part most often gotten wrong in this literature. At the end of month $t$, the training set contains only observations whose target earnings were *announced* in months $t-119$ to $t$ (rolling) or up to $t$ (expanding). The test set is month $t$'s cross-section, for earnings announced after $t$. A firm whose earnings are announced in $t+1$ is therefore in the test set at $t$ and not in the training set, even if its fiscal period ended earlier. It is the forecasting analogue of the point-in-time rules used throughout the book: a feature or target enters only once it was public.\n\n### The Accuracy Measure: ML Superiority {#sec-mlef-superiority}\n\nFollowing @bradshaw2012man, accuracy is measured relative to analysts on a per-dollar-of-price basis. For firm $i$, forecast month $t$, and fiscal period ending $T$,\n\n$$\n\\text{ML Superiority}_{i,t} = \\left|\\frac{\\text{EPS}_{i,T} - \\text{AF}_{t}(\\text{EPS}_{i,T})}{P_{i,t}}\\right| - \\left|\\frac{\\text{EPS}_{i,T} - \\text{ML}_{t}(\\text{EPS}_{i,T})}{P_{i,t}}\\right|,\n$$ {#eq-mlef-superiority}\n\nwhere both price-scaled errors are winsorised to $[-1, 1]$, FQ errors are annualised (multiplied by four), and the result is reported in percentage points. A positive value means the machine's absolute error is smaller than the analysts'. A model's ML Superiority is the panel average, with standard errors two-way clustered by firm and year.\n\nThe measure has an economic reading: 0.10 percentage points is a reduction in the absolute forecast error of 1 cent for a \\$10 stock. For scale, the median $|\\text{EPS}/P|$ in the sample is 6.07% (FQ, annualised) and 6.43% (FY2). The paper uses 1 cent per \\$10 of price as its threshold for an economically meaningful improvement, motivated by evidence that investors discount earnings beats smaller than a cent [@keung2010does].\n\nBecause @eq-mlef-superiority is an *absolute*-error comparison, the forecast that maximises it is the conditional *median* of earnings, not the conditional mean. This one fact explains the single largest result in the paper.\n\n### Direct and Indirect Forecasts {#sec-mlef-indirect}\n\nA machine can use analysts' forecasts in three ways:\n\n1.  **Direct without analysts.** Regress $\\text{EPS}_{i,T}$ on non-analyst features: $\\widehat{\\text{EPS}} = \\hat f(X)$.\n2.  **Direct with analysts.** Add the analyst variables to $X$: $\\widehat{\\text{EPS}} = \\hat f(X, \\text{AF}, \\dots)$.\n3.  **Indirect** [@frankel1998accounting; @so2013new]. Forecast the analyst *error* and correct the consensus:\n$$\n\\widehat{\\text{EPS}}_{i,T} = \\text{AF}_{t} + \\hat g(X, \\text{AF}, \\dots), \\qquad \\hat g = \\arg\\min_g \\sum L\\big(\\text{EPS}_{i,T} - \\text{AF}_{t},\\; g(\\cdot)\\big).\n$$ {#eq-mlef-indirect}\n\nFor an *unpenalised linear* model with $\\text{AF}$ among the regressors, the direct-with-analysts and indirect forecasts are identical: subtracting $\\text{AF}$ from the target only shifts its coefficient by one. The two approaches differ for every model that shrinks or approximates. A ridge or lasso penalty shrinks coefficients toward zero, so the direct model is shrunk toward \"ignore the analyst\" while the indirect model is shrunk toward \"trust the analyst\". A tree ensemble has to rebuild the near-identity map from $\\text{AF}$ to $\\text{EPS}$ out of piecewise-constant steps in the direct approach, while in the indirect approach the identity is free and every split is spent on the bias. Since the consensus is an excellent forecast to begin with, \"trust the analyst unless the data say otherwise\" is the better default. @sec-mlef-sim-grid verifies both statements.\n\n### The 3,024-Model Experiment {#sec-mlef-grid}\n\nEvery model minimises an average loss plus a penalty over the estimation window,\n\n$$\n\\hat f = \\arg\\min_{f}\\; \\frac{1}{N}\\sum_{i} L\\big(y_i, f(X_i)\\big) + G(f;\\gamma),\n$$\n\nand the paper varies nine choices that existing studies make differently:\n\n| Choice set | Options |\n|------------------------------------|------------------------------------|\n| Loss function $L$ | MAE; MSE; MSE with the target trimmed at 1%/99% in the training set |\n| Algorithm ($G$) | OLS, Lasso, Ridge, Elastic Net, random forest (RF), gradient-boosted regression trees (GBRT) |\n| Cross-validation for hyperparameters | Time-series (validation after training); panel 5-fold |\n| Estimation window | Rolling 10 years; expanding |\n| Hyperparameter tuning frequency | Once at the beginning; annually |\n| Model refit frequency | Monthly; yearly |\n| Forecasting approach | Direct; indirect (@eq-mlef-indirect) |\n| Predictor set | With analyst variables; without |\n| Scaling in the forecasting step | None; EPS variables divided by price |\n| Forecast period | FQ; FY2 |\n\n: The nine specification choices. OLS has no hyperparameters, so it has 144 configurations; each other algorithm has 576, for 3,024 models in total. {#tbl-mlef-choices}\n\nThe authors report that estimating all 3,024 models took about five years of machine time on university servers.\n\n### Result 1: Most Machine Forecasts Lose to Analysts {#sec-mlef-result-specs}\n\nOf the 3,024 models, 79% have negative ML Superiority (88% for FQ and 70% for FY2). The distribution has a long left tail reaching below $-15$ percentage points and a narrow right tail that never exceeds $+0.65$. @tbl-mlef-what-matters, reproduced from the replication package, averages ML Superiority over all models sharing a given option and reports the best and worst option in each choice set.\n\n| Choice set | Best option | Worst option | Superiority (best) | Superiority (worst) | Difference | Run time diff. (hours) |\n|-----------|-----------|-----------|----------:|----------:|----------:|----------:|\n| Loss function | MAE | MSE | $-0.37$ | $-6.69$ | 6.32 | 14.9 |\n| Algorithm | RF | OLS | $-1.22$ | $-4.58$ | 3.36 | 15.4 |\n| Forecasting approach | Indirect | Direct | $-1.51$ | $-3.05$ | 1.55 | $-0.5$ |\n| CV scheme | Time-series | K-fold | $-1.70$ | $-3.17$ | 1.47 | $-4.6$ |\n| Predictor set | With analysts | Without | $-2.11$ | $-3.39$ | 1.28 | 0.0 |\n| Scaling | Price | None | $-2.30$ | $-2.78$ | 0.48 | $-0.7$ |\n| Estimation window | Rolling | Expanding | $-2.40$ | $-2.67$ | 0.27 | $-7.7$ |\n| Refit frequency | Monthly | Yearly | $-2.49$ | $-2.59$ | 0.10 | 4.4 |\n| Tuning frequency | Annual | Beginning | $-2.39$ | $-2.48$ | 0.09 | 21.2 |\n\n: Average ML Superiority (percentage points) by specification choice, all 3,024 models. Source: `Specification_Comparison.tex` in the replication package. {#tbl-mlef-what-matters}\n\nFour choices dominate:\n\n-   **The loss function.** None of the 1,008 MSE models beats analysts; 46% of the MAE models do. Earnings scaled by price have fat tails and a long *left* tail from losses and write-offs, so the conditional mean sits below the conditional median. An MSE model chases the mean and is penalised by an absolute-error yardstick; trimming the target helps (16% of trimmed-MSE models win) but does not fix the misalignment.\n-   **The indirect approach** raises the share of winning models from 12% (direct) to 39%.\n-   **Time-series cross-validation** beats 5-fold cross-validation. With overlapping targets (the same FY2 EPS is the target for up to 24 monthly forecasts of the same firm), a shuffled $k$-fold split puts near-duplicates of each validation row in the training folds, the validation error is too optimistic, and tuning picks models that are too flexible. This is the concern @bertomeu2020machine raises for accounting data.\n-   **Analyst inputs.** Only 4% of the models without analyst variables beat analysts.\n\nRestricting attention to MAE loss, the indirect approach, and time-series CV leaves 176 models, *all* of which beat analysts. The remaining choices (window, refit and tuning frequency) change accuracy by a tenth of a percentage point or less but change run time by up to 21 hours, so the cheap options are fine.\n\n### Result 2: The Best Model, and Where Its Edge Comes From {#sec-mlef-result-best}\n\n| Algorithm | FQ superiority | FY2 superiority |\n|-----------|------------:|------------:|\n| OLS | 0.113 | 0.267 |\n| Lasso | 0.113 | 0.300 |\n| Ridge | 0.113 | 0.306 |\n| Elastic net | 0.113 | 0.309 |\n| Random forest | 0.116 | 0.365 |\n| GBRT | **0.201** | **0.601** |\n\n: Best specification by algorithm, among models with MAE loss, time-series CV and no price scaling. Every winner uses the indirect approach and monthly refitting, and all but FY2 GBRT (expanding window) use the rolling window. Source: `Best_SpecsFQ.tex`, `Best_SpecsFY2.tex`, whose header swaps the labels of the refit and tuning-frequency columns. {#tbl-mlef-best}\n\nGBRT wins for both horizons (@tbl-mlef-best). @tbl-mlef-approach isolates the role of analysts by holding the best specification fixed and changing only how analyst information enters.\n\n| Approach | OLS | Lasso | Ridge | EN | RF | GBRT |\n|-----------------|--------:|--------:|--------:|--------:|--------:|--------:|\n| FQ, direct without analysts | $-1.722$ | $-1.721$ | $-1.724$ | $-1.731$ | $-2.629$ | $-1.132$ |\n| FY2, direct without analysts | $-0.460$ | $-0.434$ | $-0.461$ | $-0.420$ | $-0.558$ | $0.205$ |\n| FQ, direct with analysts | $-0.113$ | $-0.117$ | $-0.120$ | $-0.113$ | $-2.369$ | $0.092$ |\n| FY2, direct with analysts | $0.167$ | $0.165$ | $0.168$ | $0.168$ | $-0.452$ | $0.536$ |\n| FQ, indirect | $0.113$ | $0.113$ | $0.113$ | $0.113$ | $0.116$ | $0.201$ |\n| FY2, indirect | $0.267$ | $0.300$ | $0.306$ | $0.309$ | $0.365$ | $0.601$ |\n\n: ML Superiority (percentage points) by approach and algorithm; all entries significant at 5% or better. Source: `BradshawT3FullBestnoana.tex`. {#tbl-mlef-approach}\n\nThree lessons follow. Without analyst information, no model beats analysts for FQ, and only GBRT does so for FY2, by 0.2 points (2 cents per \\$10 stock). With analyst variables as inputs, the direct approach helps but random forests still lose badly, because averaging tree leaves cannot reproduce the near-linear map from forecast to outcome. The indirect approach makes *every* algorithm beat analysts and compresses the gap between the worst and best algorithm. In short, the machine's edge is a correction to the analyst, not a substitute for the analyst.\n\nWhat does the correction look like? The paper decomposes the GBRT predicted bias with SHAP values. For FQ the most important features are the lagged realised analyst error (14.0% of total mean absolute SHAP), price (7.3%), the consensus itself (6.5%), size (4.7%), and the one-month return (4.5%). For FY2 they are the consensus (24.1%), price (14.0%), the three-month analyst revision (6.4%), six-month momentum (5.1%), and free cash flow over operating cash flow (5.0%). The ten most important features account for half (FQ) and two-thirds (FY2) of the total. The SHAP profile of the lagged analyst error is S-shaped: steeper than the linear coefficient near zero and flattening in the tails. Analysts' errors are persistent (they under-correct their own past mistakes), and the machine learns the persistence nonlinearly. Price and the level of the forecast enter because analyst errors vary systematically with both, in line with the conditional biases documented by @binsbergen2023man and with the characteristics-based forecasts of analyst errors in @so2013new.\n\n### Result 3: When the Machine's Edge Is Economically Large {#sec-mlef-result-when}\n\nThe average superiority of 0.20 points (FQ) and 0.60 points (FY2) hides large cross-sectional differences.\n\n**Firm size.** Sorting monthly on market capitalisation:\n\n| Size quintile | Q1 (small) | Q2 | Q3 | Q4 | Q5 (large) |\n|-------------|---------:|---------:|---------:|---------:|---------:|\n| FQ | 0.569 | 0.194 | 0.106 | 0.072 | 0.062 |\n| FY2 | 1.712 | 0.677 | 0.362 | 0.189 | 0.064 |\n\n: ML Superiority of the best model (GBRT, indirect) by size quintile, percentage points (recomputed in @sec-mlef-replication). {#tbl-mlef-size}\n\nFor the largest quintile, which holds about 87% of market capitalisation, the gain is about 0.6 cents per \\$10 stock: real but economically trivial. For the smallest quintile it is 5.7 cents (FQ) and 17 cents (FY2). A multivariate Fama--MacBeth regression of superiority on percentile ranks of firm attributes (Newey--West, 24 lags) confirms that small size, high idiosyncratic volatility, many business segments, wide bid--ask spreads, and (for FY2) external financing and accrual volatility are associated with a larger machine edge. These are the information-uncertainty and analyst-incentive variables of the analyst-bias literature.\n\n**Horizon.** In the working-paper version, GBRT's superiority for FQ forecasts made one month before the announcement is only 0.086 points, rising to 0.27 at three months; for FY2 it is 0.52 at twelve months and peaks at 0.67 at nineteen months. Analysts are hard to beat on the next quarter.\n\n**Time.** The 10-year rolling average of the FQ superiority falls from about 0.31 points in 2000 to about 0.10 by 2020 (the decade averages in our recomputation are 0.30, 0.19 and 0.10 for FQ and 0.84, 0.59 and 0.33 for FY2), but it stays significantly positive. Analysts appear to have removed part of their own predictable error over time, which is what one would expect if they adopt the same tools.\n\n**Thin coverage.** For the two smallest size quintiles, with one to three analysts, a GBRT model that does *not* use analyst inputs is significantly *worse* than analysts for forecasts made one or two months before the announcement (up to six months when there are three analysts), and significantly better only from eight months ahead (smallest firms, a single analyst) or, in most cells, ten months ahead (package table `Superiority_low_coverage.tex`). Even one or two analysts carry information a machine cannot reconstruct from financial statements, until the forecast horizon is long.\n\nThese are the \"when not to\" conditions in the title. For large firms and short horizons, the consensus is about as good as the best machine, costs nothing to compute, and is reproducible. For small firms and long horizons the machine is materially better.\n\n### Result 4: Which Expectation Does the Market Use? {#sec-mlef-result-market}\n\nThe market test regresses size-adjusted three-day announcement returns on earnings surprises built from each expectation. With $\\text{SUE}^{X} = (\\text{EPS} - X_{t-1})/P_{t-1}$ for $X \\in \\{\\text{AF}, \\text{ML}\\}$, measured at the month end before the announcement,\n\n$$\nR_{d-1,d+1} = c + \\beta\\,\\text{SUE} + \\varepsilon .\n$$\n\nAcross the 1,512 FQ models, the rank correlation between a model's ML Superiority and the earnings-response coefficient of its SUE is 0.97, and 90% of the models produce a *smaller* ERC than the analyst-based SUE. More accurate forecasts produce surprises that look more like news to the market, so a poorly specified machine forecast is a worse proxy for the market's expectation than the consensus.\n\nTo estimate *how much* weight the market puts on each forecast, suppose the market's surprise is a weighted combination\n$$\n\\text{SUE}^{M} = w_{AF}\\,\\text{SUE}^{AF} + w_{ML}\\,\\text{SUE}^{ML}, \\qquad R = c + \\beta^{M}\\,\\text{SUE}^{M} + \\varepsilon .\n$$ {#eq-mlef-mix}\nWrite $G = (\\text{ML} - \\text{AF})/P$, so that $\\text{SUE}^{AF} = \\text{SUE}^{ML} + G$. Substituting,\n$$\nR = c + \\underbrace{\\beta^{M}(w_{AF}+w_{ML})}_{\\beta_1}\\,\\text{SUE}^{ML} + \\underbrace{\\beta^{M} w_{AF}}_{\\beta_2}\\, G + \\varepsilon ,\n\\qquad\nR = c + \\underbrace{\\beta^{M}(w_{AF}+w_{ML})}_{\\gamma_1}\\,\\text{SUE}^{AF} \\underbrace{- \\beta^{M} w_{ML}}_{\\gamma_2}\\, G + \\varepsilon ,\n$$ {#eq-mlef-erc}\nso that\n$$\n\\frac{\\beta_2}{\\beta_1} = \\frac{w_{AF}}{w_{AF}+w_{ML}}, \\qquad -\\frac{\\beta_2}{\\gamma_2} = \\frac{w_{AF}}{w_{ML}} .\n$$ {#eq-mlef-weights}\nIf prices fully undo the predictable analyst error, $\\beta_2 = 0$. If the market simply uses the consensus, $\\beta_2 = \\beta_1$. The gap $G$ is the machine-predicted analyst bias, so the regression asks whether the market reacts to the part of the analyst surprise that was predictable in advance.\n\n| | (1) | (2) | (3) | (4) | (5) |\n|----------------------|--------:|--------:|--------:|--------:|--------:|\n| $\\text{SUE}^{ML}$ | 0.241 (5.89) | | 0.245 (5.62) | 0.181 (5.77) | 0.180 (9.44) |\n| $\\text{SUE}^{AF}$ | | 0.209 (5.91) | | | |\n| Bias $G$ | | | 0.093 (5.36) | 0.087 (5.22) | 0.099 (4.83) |\n| $\\text{SUE}^{ML}\\times$ Size rank | | | | 0.232 (3.60) | |\n| $G\\times$ Size rank | | | | $-0.086$ ($-2.19$) | |\n| $\\text{SUE}^{ML}\\times$ IO rank | | | | | 0.172 (2.00) |\n| $G\\times$ IO rank | | | | | $-0.071$ ($-1.54$) |\n| $R^2$ (%) | 2.33 | 2.20 | 2.45 | 2.67 | 2.72 |\n| Observations | 326,886 | 326,886 | 326,886 | 326,886 | 325,648 |\n\n: Earnings-response tests (published Table 7, recomputed in @sec-mlef-replication). Returns and SUEs in percent, trimmed at 1%/99% per quarter; $t$-statistics two-way clustered by firm and quarter. Size and IO are quarterly percentile ranks; their main effects are included but not shown. {#tbl-mlef-erc}\n\nColumn (3) gives $\\beta_2/\\beta_1 = 0.093/0.245 = 0.38$: in the average stock the market behaves as if it puts 38% relative weight on the consensus and 62% on the machine forecast. The market \"largely, but not fully\" corrects the predictable analyst bias. The interactions show where the correction is incomplete. Evaluating @eq-mlef-weights at the bottom and top size ranks, the analyst weight is $0.087/0.181 \\approx 0.48$ for the smallest stocks and $(0.087-0.086)/(0.181+0.232) \\approx 0$ for the largest. For institutional ownership it is $0.099/0.180 \\approx 0.55$ at the bottom rank and $(0.099-0.071)/(0.180+0.172) \\approx 0.08$ at the top. Large, institutionally held stocks are priced as if the analyst bias were already removed. Small stocks held by retail investors are priced as if about half of it were taken at face value.\n\n**The bias is a return predictor.** If part of the predictable bias is not priced before the announcement, sorting stocks on $G$ should predict returns. The paper forms quintiles on $G$ each quarter and tracks the cumulative size-adjusted return of the high-minus-low portfolio from 40 trading days before to 252 days after the announcement. For small, low-IO stocks the spread is about 4.7% by the announcement day and keeps rising to about 10% by roughly 170 trading days (eight to nine months) before levelling off. For small, high-IO stocks it reaches about 7%. For large stocks it is 1--3% and mostly insignificant. Prices eventually catch up with the machine forecast, but slowly, and only where the bias is large and sophisticated investors are scarce.\n\n**Additional working-paper results.** The working paper also shows that implied cost of capital computed from machine FY2 forecasts tracks cross-sectional expected returns better than ICC from analysts' forecasts and better than the characteristic-based measure of @lee2021evaluating, with the gain concentrated in small firms. It also defines an \"analyst value added\" (the accuracy gain from adding analyst inputs to the machine), which is larger for small firms and for firms with complex filings and does not decline over time.\n\n## Replication from the Authors' Data {#sec-mlef-replication}\n\nThe replication package contains the monthly GBRT-indirect forecasts (`DataShare.dta`, 279 MB, 1.16 million firm-months) together with realised EPS, the consensus, price, size, institutional ownership, the firm attributes, and size-adjusted three-day announcement returns. It also includes a summary of all 3,024 models (`Specification_Sumstats.csv`). The model training code is not included, so the replicable part is everything downstream of the forecasts: the accuracy measure, the size sorts, the time trend and the market tests. The cell below is our own implementation. It is not evaluated when the book is built because the data file is not distributed with the book. Download the package from the DOI above to run it.\n\n::: {#mlef-replicate .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Recompute ML Superiority, size sorts and ERC weights from DataShare.dta\"}\nimport numpy as np\nimport pandas as pd\nfrom linearmodels import PanelOLS\n\ndf = pd.read_stata(\"DataShare.dta\")\ndf[\"fdate\"] = df[\"Forecast_Date\"].astype(int)\ndf[\"year\"] = df[\"fdate\"] // 100\n\n\ndef clustered_mean(y, firm, time):\n    \"\"\"Mean of y with standard errors two-way clustered by firm and time.\"\"\"\n    d = pd.DataFrame({\"y\": y.values, \"firm\": firm.values, \"time\": time.values}).dropna()\n    d = d.set_index([\"firm\", \"time\"]).assign(const=1.0)\n    r = PanelOLS(d[\"y\"], d[[\"const\"]]).fit(\n        cov_type=\"clustered\", cluster_entity=True, cluster_time=True)\n    return r.params[\"const\"], r.tstats[\"const\"]\n\n\nfor h, k in [(\"FQ\", 4), (\"FY2\", 1)]:            # k annualises quarterly errors\n    d = df.dropna(subset=[f\"Actual_{h}\", f\"Pred_{h}\", f\"Analyst_{h}\", \"prc\"]).copy()\n    afe = (k * (d[f\"Actual_{h}\"] - d[f\"Analyst_{h}\"]) / d[\"prc\"]).clip(-1, 1)\n    mle = (k * (d[f\"Actual_{h}\"] - d[f\"Pred_{h}\"]) / d[\"prc\"]).clip(-1, 1)\n    d[\"sup\"] = 100 * (afe.abs() - mle.abs())\n    print(h, \"superiority = %.3f (t = %.2f)\" % clustered_mean(d[\"sup\"], d[\"permno\"], d[\"year\"]))\n    d[\"szq\"] = d.groupby(\"fdate\")[\"size\"].transform(\n        lambda x: pd.qcut(x.rank(method=\"first\"), 5, labels=False))\n    for q in range(5):\n        s = d[d[\"szq\"] == q]\n        print(\"   size Q%d: %.3f (t = %.2f)\" % (q + 1, *clustered_mean(s[\"sup\"], s[\"permno\"], s[\"year\"])))\n\n# Market tests: size-adjusted 3-day announcement returns on SUE^ML and the bias G\ne = df.dropna(subset=[\"Announcement_Ret_Size_Adj_FQ\", \"Actual_FQ\", \"Pred_FQ\",\n                      \"Analyst_FQ\", \"prc\"]).copy()\nann = pd.to_datetime(e[\"Announcement_Date_Johnson_FQ\"])\ne[\"tq\"] = (ann.dt.year - 1960) * 4 + (ann.dt.month - 1) // 3\ne[\"afe\"] = 4 * (e[\"Actual_FQ\"] - e[\"Analyst_FQ\"]) / e[\"prc\"]\ne[\"mle\"] = 4 * (e[\"Actual_FQ\"] - e[\"Pred_FQ\"]) / e[\"prc\"]\nfor v in [\"mle\", \"afe\", \"Announcement_Ret_Size_Adj_FQ\"]:   # trim 1%/99% by quarter\n    lo = e.groupby(\"tq\")[v].transform(lambda x: x.quantile(0.01))\n    hi = e.groupby(\"tq\")[v].transform(lambda x: x.quantile(0.99))\n    e[v + \"_t\"] = 100 * e[v].where(e[v].between(lo, hi))\ne = e.dropna(subset=[\"mle_t\", \"afe_t\", \"Announcement_Ret_Size_Adj_FQ_t\"])\ne[\"bias_t\"] = e[\"afe_t\"] - e[\"mle_t\"]                       # = G = 4 (ML - AF) / P\ne = e.set_index([\"permno\", \"tq\"]).assign(const=1.0)\n\n\ndef erc(xs):\n    return PanelOLS(e[\"Announcement_Ret_Size_Adj_FQ_t\"], e[xs + [\"const\"]]).fit(\n        cov_type=\"clustered\", cluster_entity=True, cluster_time=True)\n\n\nb = erc([\"mle_t\", \"bias_t\"]).params\ng = erc([\"afe_t\", \"bias_t\"]).params\nprint(\"w_AF / (w_AF + w_ML) = %.3f\" % (b[\"bias_t\"] / b[\"mle_t\"]))\nprint(\"w_AF / w_ML          = %.3f\" % (-b[\"bias_t\"] / g[\"bias_t\"]))\n```\n:::\n\n\nRunning this code on the package data (October 2026, about one minute) reproduces the published numbers:\n\n| Statistic | Published | Recomputed |\n|------------------------------------------|-----------:|-----------:|\n| FQ ML Superiority, GBRT indirect | 0.201 ($t$ = 8.71) | 0.201 ($t$ = 8.85) |\n| FY2 ML Superiority, GBRT indirect | 0.601 ($t$ = 7.48) | 0.601 ($t$ = 7.60) |\n| FQ superiority, size Q1 / Q5 | 0.57 / 0.06 (figure) | 0.569 / 0.062 |\n| FY2 superiority, size Q1 / Q5 | 1.71 / 0.06 (figure) | 1.712 / 0.064 |\n| ERC on $\\text{SUE}^{ML}$, col. (1) | 0.241 (5.89) | 0.241 (5.89) |\n| ERC on $\\text{SUE}^{AF}$, col. (2) | 0.209 (5.91) | 0.209 (5.91) |\n| $\\beta_1$, $\\beta_2$, col. (3) | 0.245, 0.093 | 0.245, 0.093 |\n| $w_{AF}/(w_{AF}+w_{ML})$ | --- | 0.381 |\n| $w_{AF}/w_{ML}$ | --- | 0.614 |\n| Share of 3,024 models with superiority $\\le 0$ | \"80%\" | 79.1% |\n\n: Replication of headline results. Both versions cluster by firm and forecast year; the small $t$-statistic differences for the superiority means come from the small-sample adjustments in Stata's `vcemway` and in `linearmodels`. {#tbl-mlef-replication}\n\nTwo additional facts from the package are worth recording. The mean analyst error $(\\text{EPS} - \\text{AF})/P$ is $-1.4\\%$ (FQ, annualised) and $-2.8\\%$ (FY2), the familiar optimism that rises with horizon. The two weights in @eq-mlef-weights are also internally consistent: $0.381/(1-0.381) = 0.615 \\approx 0.614$.\n\nOne further calculation is ours, not the paper's, and is motivated by @sec-mlef-sim-erc below. Regressing the trimmed realised analyst error $4(\\text{EPS}-\\text{AF})/P$ on the trimmed bias $G$ in the same ERC sample gives a slope of $\\hat\\lambda = 0.87$ (two-way clustered $t$ = 12.8), so the machine's bias estimate is somewhat too dispersed. Under the assumptions of @eq-mlef-lambda, the market's weight on the consensus relative to the rational forecast is then about $1 - (1 - 0.38)/0.87 \\approx 0.28$ rather than 0.38. Investors appear to correct even more of the predictable analyst error than the headline estimate suggests.\n\n## A Simulation That Shows Each Mechanism {#sec-mlef-sim}\n\nThe replication confirms the numbers, but it cannot show *why* they come out this way, because nobody knows the true analyst bias or the true market expectation in real data. In a simulation we do know them. The design below builds the paper's key ingredients into a firm-year panel and then checks whether the paper's procedures recover them:\n\n-   Earnings yields have a firm-specific level, persistent fundamentals with nonlinear effects, fat-tailed noise that is larger for small firms, and occasional large write-offs that skew the distribution to the left.\n-   Analysts know something the machine does not: a private signal about part of the earnings shock, more precise at shorter horizons.\n-   Analysts also make **predictable** errors: they are optimistic about small and low-priced firms (more so at longer horizons) and only partly correct their past errors, through an S-shaped function of the lagged error, mirroring the SHAP profile in @sec-mlef-result-best.\n-   Each announcement is forecast three times (12, 6 and 1 month ahead), so targets overlap across rows, as with I/B/E/S monthly forecasts.\n\n::: {#mlef-sim-panel .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Simulate a firm-year panel with informed but predictably biased analysts\"}\nimport time\nimport warnings\nimport numpy as np\nimport pandas as pd\nimport statsmodels.api as sm\nfrom sklearn.ensemble import HistGradientBoostingRegressor\nfrom sklearn.linear_model import Lasso\nfrom sklearn.model_selection import KFold\nfrom sklearn.preprocessing import StandardScaler\nfrom plotnine import (ggplot, aes, geom_col, geom_hline, coord_flip, facet_wrap,\n                      labs, theme_minimal, theme, scale_fill_manual)\n\nwarnings.filterwarnings(\"ignore\")\nmlef_t0 = time.time()\nrng = np.random.default_rng(2026)\nN_FIRMS, N_YEARS = 500, 15\nHORIZONS = {12: 0.3, 6: 0.6, 1: 0.9}      # months ahead -> share of eta analysts know\n\nsize = rng.normal(0, 1, N_FIRMS)           # persistent log-size (z-score)\nlevel = rng.normal(0.06, 0.03, N_FIRMS)    # firm-specific earnings-yield level\nx = rng.normal(0, 1, (N_FIRMS, 3))         # persistent fundamentals\nlag_err = np.zeros(N_FIRMS)                # last realised analyst error (scaled)\nlag_eps = level.copy()\nframes = []\nfor yr in range(N_YEARS):\n    size = 0.95 * size + rng.normal(0, 0.3, N_FIRMS)\n    x = 0.8 * x + rng.normal(0, 0.6, x.shape)\n    price = np.exp(2.5 + 0.6 * size + rng.normal(0, 0.4, N_FIRMS))\n    mu = (level + 0.012 * x[:, 0] - 0.008 * np.maximum(x[:, 1], 0)\n          + 0.006 * np.tanh(2 * x[:, 2]))                  # fundamental earnings yield\n    vol = 0.02 * np.exp(-0.5 * size)                       # small firms are noisier\n    eta = 0.7 * vol * rng.standard_t(4, N_FIRMS)           # shock analysts partly learn\n    u = 0.7 * vol * rng.standard_t(4, N_FIRMS)             # shock nobody can forecast\n    writeoff = -1.0 * (rng.random(N_FIRMS) < 0.06) * rng.exponential(0.15, N_FIRMS)\n    eps = mu + eta + u + writeoff                          # realised EPS / price\n    for h, info in HORIZONS.items():\n        bias = (0.004 * h / 12 * (1 + np.exp(-size))       # optimism: small firms, long horizon\n                + 0.010 * (price < 8)                      # optimism: low-priced stocks\n                - 0.010 * np.tanh(lag_err / 0.02))         # sticky, S-shaped in past errors\n        af = mu + info * eta + bias + rng.normal(0, 0.003, N_FIRMS)\n        frames.append(pd.DataFrame({\n            \"firm\": np.arange(N_FIRMS), \"year\": yr, \"horizon\": h,\n            \"size\": size, \"price\": price, \"x0\": x[:, 0], \"x1\": x[:, 1], \"x2\": x[:, 2],\n            \"lag_eps\": lag_eps, \"lag_err\": lag_err, \"af\": af, \"eps\": eps,\n            # conditional median given analysts' information (write-off median is 0)\n            \"rational\": mu + info * eta,\n        }))\n    lag_err = eps - af                                     # 1-month-ahead error is next year's lag\n    lag_eps = eps\npanel = pd.concat(frames, ignore_index=True)\n\nafe = panel[\"eps\"] - panel[\"af\"]\nprint(f\"{len(panel):,} firm-horizon-years; mean analyst error {100 * afe.mean():.2f}% of price, \"\n      f\"median {100 * afe.median():.2f}%\")\nprint(\"mean analyst error by horizon (% of price):\",\n      (100 * afe.groupby(panel[\"horizon\"]).mean()).round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n22,500 firm-horizon-years; mean analyst error -1.98% of price, median -0.85%\nmean analyst error by horizon (% of price): {1: -1.48, 6: -1.95, 12: -2.51}\n```\n:::\n:::\n\n\nAll variables are already scaled by price, so \"EPS\" in the code means the earnings yield and the superiority measure of @eq-mlef-superiority needs no further scaling. The mean analyst error is negative (optimism) and grows with the horizon, as in I/B/E/S. The mean is more negative than the median because write-offs pull the mean down.\n\n### The Specification Grid {#sec-mlef-sim-grid}\n\nWe estimate fifteen models: three ways of using analysts (@sec-mlef-indirect) crossed with five algorithm--loss pairs. The linear MAE model is least-absolute-deviation regression, the lasso uses MSE with a fixed penalty on standardised features, and GBRT is scikit-learn's histogram gradient boosting with either loss. Training uses an expanding window and refits every three years, the cheap options that @tbl-mlef-what-matters says cost little accuracy.\n\n::: {#mlef-sim-grid .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Fit 15 forecasting specifications out of sample\"}\nBASE = [\"size\", \"price\", \"x0\", \"x1\", \"x2\", \"lag_eps\", \"horizon\"]\nANALYST = [\"af\", \"lag_err\"]\nAPPROACHES = [\"Direct w/o analysts\", \"Direct w/ analysts\", \"Indirect\"]\nMODELS = [(\"Linear\", \"MSE\"), (\"Linear\", \"MAE\"), (\"Lasso\", \"MSE\"),\n          (\"GBRT\", \"MSE\"), (\"GBRT\", \"MAE\")]\n\n\ndef gbrt(loss, **kw):\n    params = dict(max_iter=200, learning_rate=0.05, max_leaf_nodes=15,\n                  min_samples_leaf=50, random_state=0)\n    params.update(kw)\n    return HistGradientBoostingRegressor(\n        loss=\"squared_error\" if loss == \"MSE\" else \"absolute_error\", **params)\n\n\ndef fit_predict(train, test, approach, algo, loss):\n    \"\"\"Out-of-sample EPS/P forecast for one specification.\"\"\"\n    feats = BASE + ([] if approach == \"Direct w/o analysts\" else ANALYST)\n    y = train[\"eps\"] - train[\"af\"] if approach == \"Indirect\" else train[\"eps\"]\n    if algo == \"Linear\":\n        X = sm.add_constant(train[feats].to_numpy())\n        Xt = sm.add_constant(test[feats].to_numpy(), has_constant=\"add\")\n        if loss == \"MSE\":\n            beta = np.linalg.lstsq(X, y.to_numpy(), rcond=None)[0]\n        else:\n            beta = sm.QuantReg(y.to_numpy(), X).fit(q=0.5, max_iter=2000).params\n        pred = Xt @ beta\n    elif algo == \"Lasso\":\n        sc = StandardScaler().fit(train[feats])\n        pred = Lasso(alpha=0.002).fit(sc.transform(train[feats]), y).predict(\n            sc.transform(test[feats]))\n    else:\n        pred = gbrt(loss).fit(train[feats], y).predict(test[feats])\n    return pred + (test[\"af\"].to_numpy() if approach == \"Indirect\" else 0.0)\n\n\ndef superiority(eps, af, ml):\n    \"\"\"ML Superiority in percentage points, errors winsorised to [-1, 1].\"\"\"\n    return 100 * ((eps - af).clip(-1, 1).abs() - (eps - ml).clip(-1, 1).abs())\n\n\nFIRST_TEST, REFIT_EVERY = 6, 3\nspecs = [(a, g, l) for a in APPROACHES for g, l in MODELS]\noos = panel[panel[\"year\"] >= FIRST_TEST].copy()\npieces = {s: [] for s in specs}\nfor start in range(FIRST_TEST, N_YEARS, REFIT_EVERY):\n    train = panel[panel[\"year\"] < start]\n    test = panel[(panel[\"year\"] >= start) & (panel[\"year\"] < start + REFIT_EVERY)]\n    for s in specs:\n        pieces[s].append(fit_predict(train, test, *s))\n\nrows = []\nfor s in specs:\n    col = \" | \".join(s)\n    oos[col] = np.concatenate(pieces[s])\n    sup = superiority(oos[\"eps\"], oos[\"af\"], oos[col])\n    rows.append({\"approach\": s[0], \"model\": f\"{s[1]} ({s[2]})\",\n                 \"superiority\": sup.mean(), \"se\": sup.std() / np.sqrt(len(sup))})\ngrid = pd.DataFrame(rows)\nprint(grid.pivot(index=\"model\", columns=\"approach\", values=\"superiority\")\n          .loc[[f\"{g} ({l})\" for g, l in MODELS], APPROACHES].round(3).to_string())\nsame = np.allclose(oos[\"Direct w/ analysts | Linear | MSE\"], oos[\"Indirect | Linear | MSE\"])\nprint(f\"\\nOLS direct-with-analysts identical to OLS indirect: {same}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\napproach      Direct w/o analysts  Direct w/ analysts  Indirect\nmodel                                                          \nLinear (MSE)               -1.032               0.104     0.104\nLinear (MAE)               -0.959               0.260     0.260\nLasso (MSE)                -1.050               0.085     0.111\nGBRT (MSE)                 -0.933               0.046     0.044\nGBRT (MAE)                 -0.752               0.323     0.343\n\nOLS direct-with-analysts identical to OLS indirect: True\n```\n:::\n:::\n\n\n::: {#cell-fig-mlef-sim-grid .cell execution_count=5}\n``` {.python .cell-code}\nplot_df = grid.assign(\n    approach=pd.Categorical(grid[\"approach\"], APPROACHES),\n    model=pd.Categorical(grid[\"model\"], [f\"{g} ({l})\" for g, l in MODELS][::-1]),\n    loss=np.where(grid[\"model\"].str.contains(\"MAE\"), \"MAE loss\", \"MSE loss\"))\n(ggplot(plot_df, aes(\"model\", \"superiority\", fill=\"loss\"))\n + geom_col()\n + geom_hline(yintercept=0, linetype=\"dashed\")\n + coord_flip()\n + facet_wrap(\"~approach\", ncol=3)\n + scale_fill_manual(values=[\"#2a7f62\", \"#9a9a9a\"])\n + labs(x=\"\", y=\"ML Superiority (pp)\", fill=\"\")\n + theme_minimal()\n + theme(figure_size=(9, 3.6), legend_position=\"bottom\"))\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n![Out-of-sample ML Superiority (percentage points of price) of 15 simulated specifications. Positive values beat the analyst consensus. The dashed line marks zero.](40_ml_earnings_forecasts_files/figure-html/fig-mlef-sim-grid-output-1.png){#fig-mlef-sim-grid width=864 height=346 fig-alt='Horizontal bar chart in three panels, one per forecasting approach. In the panel without analyst inputs every bar is negative. With analyst inputs, the MSE-loss models are only slightly above zero and the MAE-loss models are clearly positive. The indirect GBRT with MAE loss has the longest positive bar.'}\n:::\n:::\n\n\nThe grid reproduces the paper's ranking, and because the data-generating process is known we can say why each result occurs.\n\n-   **No model without analyst inputs beats analysts.** Analysts observe part of the earnings shock (`eta`), and no function of the public features can recover it. This is the paper's FQ result in @tbl-mlef-approach, and it is the reason the machine's edge is a *correction* to the analyst.\n-   **MSE loses to MAE everywhere.** The 6% write-off probability pulls the conditional mean of EPS/P below the conditional median. An MSE model forecasts the mean, the superiority yardstick rewards the median, and so MSE forecasts are too pessimistic for the 94% of firms without a write-off. This is the 6.3-point loss-function gap of @tbl-mlef-what-matters in miniature.\n-   **OLS direct-with-analysts equals OLS indirect exactly**, as shown in @sec-mlef-indirect. The indirect approach matters only for models that shrink (lasso) or approximate (trees), and in the paper it is exactly for those algorithms that the switch to indirect produces the largest improvement (random forests in @tbl-mlef-approach).\n-   **Indirect GBRT with MAE loss is the best model**, because it is the only one that captures both the S-shaped persistence in analyst errors and the price threshold in analyst optimism while targeting the median.\n\n### Why Time-Series Cross-Validation {#sec-mlef-sim-cv}\n\nThe specification above fixes the GBRT hyperparameters. In practice they are tuned, and the paper finds that the way the validation sample is formed matters more than how often tuning is repeated. In our panel each announcement appears in three rows (one per horizon) with the same target and almost the same features. A shuffled $k$-fold split puts some of those rows in training and the others in validation, so the validation error rewards models that memorise firm-years. A time-series split validates only on years after the training years, as a real forecaster must.\n\n::: {#mlef-sim-cv .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Tune GBRT complexity with shuffled k-fold versus time-series validation\"}\ncv_train = panel[panel[\"year\"] < 8].reset_index(drop=True)\ncv_test = panel[panel[\"year\"] >= 8]\nFEATS = BASE + ANALYST\ncomplexity = {\"deep (leaf 3, 63 leaves)\": dict(min_samples_leaf=3, max_leaf_nodes=63),\n              \"medium (leaf 30, 31 leaves)\": dict(min_samples_leaf=30, max_leaf_nodes=31),\n              \"shallow (leaf 300, 7 leaves)\": dict(min_samples_leaf=300, max_leaf_nodes=7)}\n\n\ndef mk(p):\n    return gbrt(\"MAE\", max_iter=120, learning_rate=0.1, early_stopping=False, **p)\n\n\ndef cv_mae(p, scheme):\n    if scheme == \"Shuffled 5-fold\":\n        splits = KFold(5, shuffle=True, random_state=0).split(cv_train)\n    else:   # expanding training years, validate on the next year\n        splits = [(np.flatnonzero(cv_train[\"year\"] < v), np.flatnonzero(cv_train[\"year\"] == v))\n                  for v in (5, 6, 7)]\n    errs = []\n    for tr, va in splits:\n        a, b = cv_train.iloc[tr], cv_train.iloc[va]\n        g = mk(p).fit(a[FEATS], a[\"eps\"] - a[\"af\"]).predict(b[FEATS]) + b[\"af\"]\n        errs.append(np.mean(np.abs(b[\"eps\"] - g)))\n    return 100 * np.mean(errs)\n\n\ncv_rows = []\nfor name, p in complexity.items():\n    fitted = mk(p).fit(cv_train[FEATS], cv_train[\"eps\"] - cv_train[\"af\"])\n    pred = fitted.predict(cv_test[FEATS]) + cv_test[\"af\"]\n    cv_rows.append({\"model\": name,\n                    \"k-fold CV MAE\": cv_mae(p, \"Shuffled 5-fold\"),\n                    \"time-series CV MAE\": cv_mae(p, \"Time-series\"),\n                    \"true OOS superiority\": superiority(cv_test[\"eps\"], cv_test[\"af\"], pred).mean()})\ncv_table = pd.DataFrame(cv_rows).set_index(\"model\")\nprint(cv_table.round(3).to_string())\nprint(\"\\nk-fold picks:      \", cv_table[\"k-fold CV MAE\"].idxmin())\nprint(\"time-series picks: \", cv_table[\"time-series CV MAE\"].idxmin())\nprint(\"best out of sample:\", cv_table[\"true OOS superiority\"].idxmax())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                              k-fold CV MAE  time-series CV MAE  true OOS superiority\nmodel                                                                                \ndeep (leaf 3, 63 leaves)              2.223               2.619                 0.299\nmedium (leaf 30, 31 leaves)           2.395               2.547                 0.329\nshallow (leaf 300, 7 leaves)          2.580               2.528                 0.346\n\nk-fold picks:       deep (leaf 3, 63 leaves)\ntime-series picks:  shallow (leaf 300, 7 leaves)\nbest out of sample: shallow (leaf 300, 7 leaves)\n```\n:::\n:::\n\n\nShuffled $k$-fold reports a much lower error for the deepest model and picks it. Time-series validation reports similar errors for all three, picks the conservative model, and that model is in fact the most accurate out of sample. The leakage is invisible in the $k$-fold numbers, which is why the paper finds that tuning on a time-series split is worth about 1.5 percentage points of superiority on average.\n\n### Size and Horizon {#sec-mlef-sim-when}\n\n::: {#mlef-sim-when .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Where the best model beats analysts: size quintiles and horizons\"}\nbest = \"Indirect | GBRT | MAE\"\noos[\"sup_best\"] = superiority(oos[\"eps\"], oos[\"af\"], oos[best])\noos[\"size_q\"] = oos.groupby(\"year\")[\"size\"].transform(\n    lambda s: pd.qcut(s, 5, labels=[\"Q1 small\", \"Q2\", \"Q3\", \"Q4\", \"Q5 large\"]))\nprint(\"By size quintile (pp):\")\nprint(oos.groupby(\"size_q\", observed=True)[\"sup_best\"].mean().round(3).to_string())\nprint(\"\\nBy months to announcement (pp):\")\nprint(oos.groupby(\"horizon\")[\"sup_best\"].mean().round(3).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBy size quintile (pp):\nsize_q\nQ1 small    0.752\nQ2          0.345\nQ3          0.292\nQ4          0.189\nQ5 large    0.136\n\nBy months to announcement (pp):\nhorizon\n1     0.172\n6     0.329\n12    0.527\n```\n:::\n:::\n\n\nBoth of the paper's patterns appear, for the reasons built into the simulation. Analyst optimism and earnings noise are larger for small firms, so there is more predictable error to remove. At longer horizons the analysts' private signal is weaker and their horizon-dependent optimism is larger, so the machine's correction is worth more. Neither pattern requires the machine to know anything analysts do not know.\n\n### What the Market-Expectations Regression Identifies {#sec-mlef-sim-erc}\n\nFinally, we generate announcement returns from a market whose expectation puts weight $w_{AF} = 0.38$ on the consensus, matching @tbl-mlef-erc, and check whether @eq-mlef-weights recovers it. We do this twice. In case A, the remaining weight is on *our estimated machine forecast*, which is the assumption in @eq-mlef-mix. In case B, the remaining weight is on the *true* conditional median given analysts' information, which the machine only approximates.\n\n::: {#mlef-sim-erc .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Recover the market's weight on analysts from earnings-response regressions\"}\nW_AF, ERC_TRUE = 0.38, 1.5\nev = oos[oos[\"horizon\"] == 1].copy()       # forecasts one month before the announcement\nev[\"sue_ml\"] = ev[\"eps\"] - ev[best]\nev[\"sue_af\"] = ev[\"eps\"] - ev[\"af\"]\nev[\"gap\"] = ev[best] - ev[\"af\"]            # machine-predicted analyst bias G\n\n\ndef implied_weights(other):\n    market = W_AF * ev[\"af\"] + (1 - W_AF) * other\n    r = ERC_TRUE * (ev[\"eps\"] - market) + rng.normal(0, 0.01, len(ev))\n    f1 = sm.OLS(r, sm.add_constant(ev[[\"sue_ml\", \"gap\"]])).fit()\n    f2 = sm.OLS(r, sm.add_constant(ev[[\"sue_af\", \"gap\"]])).fit()\n    return {\"beta1\": f1.params[\"sue_ml\"], \"beta2\": f1.params[\"gap\"],\n            \"w_AF/(w_AF+w_ML)\": f1.params[\"gap\"] / f1.params[\"sue_ml\"],\n            \"w_AF/w_ML\": -f1.params[\"gap\"] / f2.params[\"gap\"]}\n\n\nerc_tab = pd.DataFrame({\n    \"truth\": {\"beta1\": ERC_TRUE, \"beta2\": ERC_TRUE * W_AF,\n              \"w_AF/(w_AF+w_ML)\": W_AF, \"w_AF/w_ML\": W_AF / (1 - W_AF)},\n    \"A: market mixes AF and the machine\": implied_weights(ev[best]),\n    \"B: market mixes AF and the true median\": implied_weights(ev[\"rational\"]),\n})\nprint(erc_tab.round(3).to_string())\n\n# Case B diagnostics: slope of the true bias on G, and its feasible estimate\nlam_true = sm.OLS(ev[\"rational\"] - ev[\"af\"], sm.add_constant(ev[\"gap\"])).fit().params[\"gap\"]\nlam_hat = sm.OLS(ev[\"eps\"] - ev[\"af\"], sm.add_constant(ev[\"gap\"])).fit().params[\"gap\"]\nratio_b = erc_tab.loc[\"w_AF/(w_AF+w_ML)\", \"B: market mixes AF and the true median\"]\nprint(f\"\\nlambda (true bias on G): {lam_true:.3f}; predicted beta2/beta1 = \"\n      f\"1 - (1 - {W_AF}) * lambda = {1 - (1 - W_AF) * lam_true:.3f}\")\nprint(f\"lambda-hat (realised analyst error on G): {lam_hat:.3f}; corrected weight = \"\n      f\"1 - (1 - {ratio_b:.3f}) / lambda-hat = {1 - (1 - ratio_b) / lam_hat:.3f}\")\nprint(f\"\\nsimulation section run time: {time.time() - mlef_t0:.0f} s\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  truth  A: market mixes AF and the machine  B: market mixes AF and the true median\nbeta1             1.500                               1.498                                   1.493\nbeta2             0.570                               0.592                                   0.803\nw_AF/(w_AF+w_ML)  0.380                               0.396                                   0.538\nw_AF/w_ML         0.613                               0.654                                   1.165\n\nlambda (true bias on G): 0.734; predicted beta2/beta1 = 1 - (1 - 0.38) * lambda = 0.545\nlambda-hat (realised analyst error on G): 0.794; corrected weight = 1 - (1 - 0.538) / lambda-hat = 0.418\n\nsimulation section run time: 39 s\n```\n:::\n:::\n\n\nCase A confirms the algebra: when the market's expectation really is a mixture of the consensus and the machine forecast, the regression recovers the weight. Case B is the caveat. Now the market mixes the consensus with the *rational* forecast, and the machine only estimates it. Write $B = (\\text{rational} - \\text{AF})/P$ for the true correction, so that the market's surprise is $\\text{SUE}^{ML} + G - (1 - w_{AF})B$. If the projection of $B$ on the machine's estimate $G$ has slope $\\lambda$, the regression delivers approximately\n$$\n\\frac{\\beta_2}{\\beta_1} \\approx 1 - (1 - w_{AF})\\,\\lambda .\n$$ {#eq-mlef-lambda}\nWith $\\lambda = 1$ (the machine's bias estimate is calibrated) the weight is recovered. Out-of-sample forecasts are typically too dispersed ($\\lambda < 1$), and the estimated analyst weight is then biased *upward*: a market that is more rational than the machine looks less rational in the regression. The printed $\\lambda$ and the predicted ratio match case B closely.\n\n$\\lambda$ is not observable, but it can be estimated. The realised analyst error $(\\text{EPS} - \\text{AF})/P$ equals $B$ plus a shock that is unpredictable at the forecast date, so regressing it on $G$ estimates $\\lambda$. Inverting @eq-mlef-lambda then gives a corrected weight, $\\hat w_{AF} = 1 - (1 - \\hat\\beta_2/\\hat\\beta_1)/\\hat\\lambda$. In the simulation the correction removes most of the bias. Fat-tailed earnings make $\\hat\\lambda$ noisy, so report it alongside the uncorrected ratio rather than in place of it.\n\n## When (Not) to Use a Machine Forecast: Practical Rules {#sec-mlef-rules}\n\nCombining the paper's results with the simulation gives a short decision list for empirical work.\n\n1.  **Large firms, next-quarter earnings:** use the consensus. The best machine improves accuracy by well under a cent per \\$10 of price, and the market prices large firms as if the analyst bias were already removed.\n2.  **Small firms or horizons beyond about six months** (FY2, long-term growth, ICC inputs): use an indirect machine forecast. The accuracy gains are economically large, and implied cost of capital improves most for exactly these firms.\n3.  **Measuring earnings news for the market** (SUE, ERC, post-announcement drift designs in @sec-sue): report both $\\text{SUE}^{AF}$ and $\\text{SUE}^{ML}$, and add the bias $G$ as a separate regressor, with the $\\hat\\lambda$ correction of @eq-mlef-lambda. A significant coefficient on $G$ means the \"surprise\" contains a part that was predictable in advance, and its decay over the following months is a return predictor in its own right.\n4.  **Building the machine:** use MAE (or another median-targeting) loss whenever accuracy is judged by absolute errors, the indirect approach, analyst inputs, and time-series validation. Choose the window, refit and tuning frequency to save computation.\n5.  **Report the specification.** Since 79% of reasonable-looking models lose to analysts, a claim that \"machine learning beats analysts\" is uninformative without the nine choices of @tbl-mlef-choices.\n\n## Vietnam: Research Design and DataCore Implementation {#sec-mlef-vn}\n\n### What Changes in Vietnam {#sec-mlef-vn-context}\n\nThe paper's conclusions depend on two facts about the US: analyst coverage is broad, and the consensus is a strong baseline. Neither holds uniformly in Vietnam.\n\n1.  **Coverage is concentrated.** Broker research (from SSI, VNDirect, VCSC, HSC, MBS and others) covers VN30 and larger VNAllShare constituents, often with one to five forecasts, and most of the HOSE, HNX and UPCoM universe has no forecast at all (@sec-sue). The paper's thin-coverage evidence is the relevant benchmark: with one to three analysts, a machine *without* analyst inputs does not beat them until the forecast is made eight to ten months or more ahead. For covered Vietnamese firms, therefore, use the indirect approach. For uncovered firms there is no consensus to correct, and the right comparison is a direct model against the seasonal random walk of @sec-sue or the cross-sectional model of @hou2012implied, not against analysts.\n2.  **The target needs care.** Vietnamese firms publish self-prepared quarterly statements (within 20 days of quarter end, 45 days for parents with consolidated statements), and audited annual statements within 90 days. Audit adjustments to annual profit can be large, and their sign is partly predictable from the same variables that predict analyst error. Forecast the *first-reported* number when studying announcement reactions, and the *audited* number when studying valuation, and never train on figures that were revised after the forecast date.\n3.  **Price scaling and the low-price bias.** Par value is VND 10,000, and many listed shares trade below par. Price is among the two or three most important predictors of analyst error in the paper, and the price distribution in Vietnam is very different, so include both the price level and a below-par indicator as features. Adjust EPS for bonus shares and stock dividends before scaling (@sec-sue).\n4.  **Short history.** A rolling ten-year window is not available for most covered firms. Use an expanding window starting in the early 2010s, pool all horizons (one row per firm-month-horizon, with months to period end as a feature), and refit yearly. The paper shows the window and refit choices barely matter for accuracy.\n5.  **Market tests under price limits.** Daily limits ($\\pm 7\\%$ HOSE, $\\pm 10\\%$ HNX, $\\pm 15\\%$ UPCoM) truncate three-day reactions to large surprises (@sec-price-limit-delayed). Use a window that extends until the first day the stock does not close at the limit, or report $[-1, +5]$ alongside $[-1, +1]$.\n6.  **Investor sophistication.** The IO interaction in @tbl-mlef-erc has a natural Vietnamese counterpart: foreign ownership as a share of the foreign-ownership limit, together with state ownership. The paper's prediction is that the market weight on analysts, $\\beta_2/\\beta_1$, is lower for stocks with high foreign ownership and higher for retail-dominated stocks.\n\n### Implementation {#sec-mlef-vn-code}\n\nThe cell below implements the indirect GBRT forecast for covered Vietnamese firms, the superiority evaluation, and the ERC weight test. DataCore method and field names follow the conventions used elsewhere in the book. Check them against your DataCore schema, because broker-consensus coverage depends on the subscription. The code was test-run on synthetic data with the same columns before being included here.\n\n::: {#mlef-vn .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Indirect GBRT earnings forecasts and market-expectation tests for Vietnam\"}\nimport numpy as np\nimport pandas as pd\nimport statsmodels.formula.api as smf\nfrom sklearn.ensemble import HistGradientBoostingRegressor\nfrom datacore import DataCoreClient\n\nclient = DataCoreClient()\n\n# 1. Inputs ---------------------------------------------------------------\n# Monthly broker consensus: one row per ticker x forecast month x fiscal period\nconsensus = client.get_analyst_consensus(\n    exchanges=[\"HOSE\", \"HNX\", \"UPCOM\"], start_date=\"2010-01-01\", end_date=\"2025-12-31\",\n    fields=[\"ticker\", \"forecast_month\", \"fiscal_period_end\", \"period_type\",   # 'FY1','FY2','Q1'\n            \"median_eps\", \"n_analysts\"])\nactuals = client.get_fundamentals(          # first-reported EPS, adjusted for bonus shares\n    exchanges=[\"HOSE\", \"HNX\", \"UPCOM\"], start_date=\"2008-01-01\", end_date=\"2025-12-31\",\n    fields=[\"ticker\", \"fiscal_period_end\", \"period_type\", \"eps_adj\", \"announcement_date\"])\nmonthly = client.get_monthly_returns(\n    exchanges=[\"HOSE\", \"HNX\", \"UPCOM\"], start_date=\"2009-01-01\", end_date=\"2025-12-31\",\n    fields=[\"ticker\", \"month\", \"close\", \"ret\", \"market_cap\", \"mom6m\",\n            \"foreign_own_pct_of_limit\", \"state_own_pct\"])\nratios = client.get_financial_ratios(       # lagged to their public release month\n    exchanges=[\"HOSE\", \"HNX\", \"UPCOM\"], start_date=\"2009-01-01\", end_date=\"2025-12-31\",\n    fields=[\"ticker\", \"month\", \"roa\", \"roe\", \"gross_margin\", \"accruals\",\n            \"leverage\", \"sales_growth\", \"book_to_market\"])\n\n\n# 2. Forecast panel -------------------------------------------------------\ndef build_panel(consensus, actuals, monthly, ratios):\n    \"\"\"One row per ticker x forecast month x target period, with features known at month end.\"\"\"\n    c = consensus.rename(columns={\"median_eps\": \"af\"}).copy()\n    c[\"forecast_month\"] = pd.to_datetime(c[\"forecast_month\"]).dt.to_period(\"M\")\n    a = actuals.rename(columns={\"eps_adj\": \"eps\"}).copy()\n    a[\"ann_month\"] = pd.to_datetime(a[\"announcement_date\"]).dt.to_period(\"M\")\n    p = c.merge(a[[\"ticker\", \"fiscal_period_end\", \"period_type\", \"eps\", \"ann_month\"]],\n                on=[\"ticker\", \"fiscal_period_end\", \"period_type\"], how=\"inner\")\n    p = p[p[\"ann_month\"] > p[\"forecast_month\"]]          # target not yet announced\n    m = monthly.assign(month=pd.to_datetime(monthly[\"month\"]).dt.to_period(\"M\"))\n    r = ratios.assign(month=pd.to_datetime(ratios[\"month\"]).dt.to_period(\"M\"))\n    p = (p.merge(m, left_on=[\"ticker\", \"forecast_month\"], right_on=[\"ticker\", \"month\"])\n          .merge(r, on=[\"ticker\", \"month\"], how=\"left\"))\n    p[\"dist\"] = (pd.to_datetime(p[\"fiscal_period_end\"]).dt.to_period(\"M\")\n                 - p[\"forecast_month\"]).apply(lambda d: d.n)\n    p[\"log_size\"] = np.log(p[\"market_cap\"])\n    p[\"below_par\"] = (p[\"close\"] < 10_000).astype(float)\n    # Most recent realised analyst error for the same period type, known at forecast month\n    # (error of the last consensus before each announcement; the paper matches the distance)\n    p = p.sort_values([\"ticker\", \"period_type\", \"forecast_month\"])\n    done = (p[[\"ticker\", \"period_type\", \"fiscal_period_end\", \"ann_month\", \"eps\", \"af\", \"close\"]]\n            .groupby([\"ticker\", \"period_type\", \"fiscal_period_end\"]).last().reset_index())\n    done[\"realised_err\"] = (done[\"eps\"] - done[\"af\"]) / done[\"close\"]\n    p = pd.merge_asof(p.sort_values(\"forecast_month\").assign(_t=lambda d: d[\"forecast_month\"].dt.start_time),\n                      done[[\"ticker\", \"period_type\", \"ann_month\", \"realised_err\"]]\n                      .assign(_t=lambda d: d[\"ann_month\"].dt.start_time).sort_values(\"_t\")\n                      .drop(columns=\"ann_month\"),\n                      on=\"_t\", by=[\"ticker\", \"period_type\"], allow_exact_matches=True)\n    p = p.rename(columns={\"realised_err\": \"lag_err\"}).drop(columns=\"_t\")\n    p = p.sort_values([\"ticker\", \"period_type\", \"fiscal_period_end\", \"forecast_month\"])\n    p[\"rev3\"] = (p.groupby([\"ticker\", \"period_type\", \"fiscal_period_end\"])[\"af\"].diff(3)\n                 / p[\"close\"])                             # three-month consensus revision\n    for col in [\"af\", \"eps\"]:\n        p[col + \"_p\"] = p[col] / p[\"close\"]               # scale by price\n    return p\n\n\nFEATURES = [\"af_p\", \"lag_err\", \"rev3\", \"dist\", \"close\", \"below_par\", \"log_size\", \"ret\",\n            \"mom6m\", \"n_analysts\", \"foreign_own_pct_of_limit\", \"state_own_pct\",\n            \"roa\", \"roe\", \"gross_margin\", \"accruals\", \"leverage\", \"sales_growth\", \"book_to_market\"]\n\n\n# 3. Indirect GBRT, expanding window, yearly refit, time-series tuning -----------\ndef tune_on_time_series(train, grid, n_val_years=2):\n    \"\"\"Pick hyperparameters by validating on the last n_val_years of announcements.\"\"\"\n    cut = train[\"ann_month\"].max().year - n_val_years\n    fit, val = train[train[\"ann_month\"].dt.year <= cut], train[train[\"ann_month\"].dt.year > cut]\n    scores = {}\n    for i, g in enumerate(grid):\n        model = HistGradientBoostingRegressor(loss=\"absolute_error\", random_state=0, **g)\n        model.fit(fit[FEATURES], fit[\"eps_p\"] - fit[\"af_p\"])\n        scores[i] = np.mean(np.abs(val[\"eps_p\"] - val[\"af_p\"] - model.predict(val[FEATURES])))\n    return grid[min(scores, key=scores.get)]\n\n\nGRID = [dict(max_iter=200, learning_rate=0.05, max_leaf_nodes=7, min_samples_leaf=200),\n        dict(max_iter=300, learning_rate=0.05, max_leaf_nodes=15, min_samples_leaf=100),\n        dict(max_iter=300, learning_rate=0.05, max_leaf_nodes=31, min_samples_leaf=50)]\n\n\ndef indirect_forecasts(panel, first_test_year=2016):\n    out = []\n    for yr in range(first_test_year, panel[\"forecast_month\"].dt.year.max() + 1):\n        start = pd.Period(f\"{yr}-01\", \"M\")\n        train = panel[panel[\"ann_month\"] < start]         # targets announced before the test year\n        test = panel[panel[\"forecast_month\"].dt.year == yr].copy()\n        if train.empty or test.empty:\n            continue\n        params = tune_on_time_series(train, GRID)\n        model = HistGradientBoostingRegressor(loss=\"absolute_error\", random_state=0, **params)\n        model.fit(train[FEATURES], train[\"eps_p\"] - train[\"af_p\"])\n        test[\"ml_p\"] = test[\"af_p\"] + model.predict(test[FEATURES])\n        out.append(test)\n    return pd.concat(out, ignore_index=True)\n\n\npanel = build_panel(consensus, actuals, monthly, ratios)\nfc = indirect_forecasts(panel)\n\n# 4. Accuracy: ML Superiority by period type and size quintile ---------------\nk = np.where(fc[\"period_type\"].str.startswith(\"Q\"), 4, 1)          # annualise quarters\nfc[\"sup\"] = 100 * ((k * (fc[\"eps_p\"] - fc[\"af_p\"])).clip(-1, 1).abs()\n                   - (k * (fc[\"eps_p\"] - fc[\"ml_p\"])).clip(-1, 1).abs())\nfc[\"size_q\"] = fc.groupby(\"forecast_month\")[\"log_size\"].transform(\n    lambda s: pd.qcut(s.rank(method=\"first\"), 5, labels=False) + 1)\nprint(fc.pivot_table(index=\"size_q\", columns=\"period_type\", values=\"sup\", aggfunc=\"mean\").round(3))\n\n# 5. Market expectations: ERC weights, with foreign-ownership interaction -----------\ncar = client.get_event_returns(              # size-adjusted CAR, window extended past limit hits\n    events=fc[[\"ticker\", \"ann_month\"]].drop_duplicates(), window=\"limit_adjusted_-1_+1\")\nev = (fc[fc[\"period_type\"] == \"Q1\"]\n        .sort_values(\"forecast_month\").groupby([\"ticker\", \"fiscal_period_end\"]).last()\n        .reset_index().merge(car, on=[\"ticker\", \"ann_month\"]))\nev[\"sue_ml\"] = 100 * 4 * (ev[\"eps_p\"] - ev[\"ml_p\"])\nev[\"gap\"] = 100 * 4 * (ev[\"ml_p\"] - ev[\"af_p\"])\nev[\"fo_rank\"] = ev.groupby(\"ann_month\")[\"foreign_own_pct_of_limit\"].rank(pct=True)\nbase = smf.ols(\"car ~ sue_ml + gap\", data=ev).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": ev[\"ticker\"].astype(\"category\").cat.codes})\ninter = smf.ols(\"car ~ sue_ml * fo_rank + gap * fo_rank\", data=ev).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": ev[\"ticker\"].astype(\"category\").cat.codes})\nratio = base.params[\"gap\"] / base.params[\"sue_ml\"]\nev[\"afe\"] = 100 * 4 * (ev[\"eps_p\"] - ev[\"af_p\"])\nlam_hat = smf.ols(\"afe ~ gap\", data=ev).fit().params[\"gap\"]\nprint(\"market weight on analysts:\", round(ratio, 3), \"| lambda-hat:\", round(lam_hat, 3),\n      \"| corrected:\", round(1 - (1 - ratio) / lam_hat, 3))\nprint(inter.params.round(3))\n```\n:::\n\n\nThe output to look for has four parts:\n\n-   The size-quintile table should show the machine's advantage concentrated in the smallest covered firms and the FY2 horizon. If superiority is negative even in the smallest quintile, check the target alignment (first-reported versus audited) before blaming the model.\n-   The weight $\\beta_2/\\beta_1$ is the share of the predictable analyst error the market takes at face value. Following @sec-mlef-sim-erc, report it together with $\\hat\\lambda$ (the slope of realised analyst errors on `gap`) and the corrected weight $1 - (1 - \\beta_2/\\beta_1)/\\hat\\lambda$.\n-   The coefficient on `gap:fo_rank` tests whether foreign-owned stocks are priced closer to the machine forecast.\n-   Sorting covered stocks into quintiles of `gap` and tracking post-announcement returns, as in @sec-mlef-result-market, tests whether the uncorrected bias is a drift predictor in Vietnam. With price limits and a retail-dominated investor base, the paper's small, low-IO result is the more relevant benchmark.\n\n## Summary {#sec-mlef-summary}\n\n@campbell2026expectations move the debate from \"can machines beat analysts?\" to \"which machine, when, and for what purpose?\" Most machine-learning earnings forecasts in a 3,024-model grid lose to the analyst consensus. The ones that win use an absolute-error loss, analyst inputs, the indirect approach of correcting the consensus, and time-series validation, and they win by removing *predictable* analyst error rather than by finding new information. The improvement is economically trivial for large firms and next-quarter earnings and large for small firms and longer horizons. Prices behave as if investors correct most of the predictable error, fully for large and institutionally held stocks and only about half for small retail-held stocks, where the remainder is priced over the following nine months. The simulation in this chapter reproduces each of these patterns from known primitives and adds one caution: the market's estimated weight on analysts is biased upward when the machine's bias estimate is too dispersed. A simple correction, applied to the authors' data, lowers the weight from 0.38 to about 0.28. For Vietnam, the paper's thin-coverage and small-firm evidence is the relevant guide: correct the consensus where it exists, benchmark against time-series models where it does not, and expect the largest gains, and the largest mispricing, among small, retail-dominated stocks.\n\n",
    "supporting": [
      "40_ml_earnings_forecasts_files"
    ],
    "filters": [],
    "includes": {}
  }
}